#pragma once
#include <string_view>
#include <optional>
#include <taul/grammar.h>
#include <taul/export_fetcher.h>

namespace taul::fetchers {
    namespace details {
        struct sigs_singleton_traits final {
            static constexpr std::string_view get_serial_str() noexcept {
                return "TAULAQAAAAAAAAALAAAAAAAAAAkAAAAAAAAACgAAAElERU5USUZJRVIABwAAAFJfQVJST1cABwAAAExfUk9VTkQABwAAAFJfUk9VTkQACAAAAExfU1FVQVJFAAgAAABSX1NRVUFSRQAFAAAAQ09NTUEACQAAAERCTF9DT0xPTgAFAAAAQ09MT04ABQAAAFNMQVNIAAoAAABXSElURVNQQUNFAQgAAABUb3BMZXZlbAAEAAAARXhwcgMEAAAAQXJncwADAAAAQXJnAAgAAABDYWxsU3VmZgAGAAAAUGFyYW1zAAUAAABQYXJhbQAKAAAAUmV0dXJuVHlwZQACAAAASWQAJwAAAAAAAAABABEABAAAAAAAAAABDAARAP////8BDgARAP////8BDwARAP////8BEQARAP////8MABEAAAAAAAAAAAAMABEAAQAAAAAAAAABDQARAP////8NABEAAQAAAAAAAAAAJAAAACUAAAAADgARAAEAAAAAAAAAAEEAAABaAAAAAA4AEQABAAAAAAAAAABfAAAAXwAAAAAOABEAAQAAAAAAAAAAYQAAAHoAAAAADgARAAEAAAAAAAAAAIAAAAD/1wAAAA4AEQABAAAAAAAAAAAA4AAA//8QAAAPABEAAAAAAAAAAAAPABEAAgAAAAAAAAABEAARAP////8BDwARAP////8QABEAAQAAAAAAAAAAMAAAADkAAAAAEAARAAEAAAAAAAAAAEEAAABaAAAAABAAEQABAAAAAAAAAABfAAAAXwAAAAAQABEAAQAAAAAAAAAAYQAAAHoAAAAAEAARAAEAAAAAAAAAAIAAAAD/1wAAABAAEQABAAAAAAAAAAAA4AAA//8QAAARABEAAAAAAAAAAAARABEAAQAAAAAAAAABEgARAP////8SABEAAgAAAAAAAAAAJAAAACQAAAAAARMAEQD/////EwARAAQAAAAAAAAAAGkAAABpAAAAAABuAAAAbgAAAAAAaQAAAGkAAAAAAHQAAAB0AAAAABMAEQAIAAAAAAAAAABhAAAAYQAAAAAAcwAAAHMAAAAAAHMAAABzAAAAAABpAAAAaQAAAAAAZwAAAGcAAAAAAG4AAABuAAAAAABlAAAAZQAAAAAAcgAAAHIAAAAAAgARAAIAAAAAAAAAAC0AAAAtAAAAAAA+AAAAPgAAAAADABEAAQAAAAAAAAAAKAAAACgAAAAABAARAAEAAAAAAAAAACkAAAApAAAAAAUAEQABAAAAAAAAAABbAAAAWwAAAAAGABEAAQAAAAAAAAAAXQAAAF0AAAAABwARAAEAAAAAAAAAACwAAAAsAAAAAAgAEQACAAAAAAAAAAA6AAAAOgAAAAAAOgAAADoAAAAACQARAAEAAAAAAAAAADoAAAA6AAAAAAoAEQABAAAAAAAAAAAvAAAALwAAAAALABEAAQAAAAAAAAABFAARAP////8UABEAAgAAAAAAAAABFgARAP////8BFQARAP////8VABEAAAAAAAAAAAAVABEAAgAAAAAAAAABFgARAP////8BFQARAP////8WABEAAQAAAAAAAAABFwARAP////8XABEAAQAAAAAAAAAACQAAAAoAAAAAFwARAAEAAAAAAAAAAA0AAAANAAAAABcAEQABAAAAAAAAAAAgAAAAIAAAAAAcAAAAAAAAAAMAEgADAAAAAAAAAAEEABIAAAAAAAEMABIA/////wACABIAAgASAAEMABIAAAAAAAAAAAAMABIAAQAAAAAAAAABBwASAAAAAAAEABIAAwAAAAAAAAABDQASAP////8BDgASAP////8DDQASAAEAAAAAAAAAAQsAEgAAAAAADgASAAAAAAAAAAAADgASAAIAAAAAAAAAAQ8AEgD/////AQ4AEgD/////DwASAAMAAAAAAAAAAgAAAAD/////AAoAEQAKABEAAAELABIAAAAAAA8AEgADAAAAAAAAAAIBAAAA/////wAJABEACQARAAABCwASAAAAAAAPABIAAwAAAAAAAAACAgAAAP////8ACAARAAgAEQAAAQsAEgAAAAAADwASAAQAAAAAAAAAAgMAAAD/////AAUAEQAFABEAAAEQABIA/////wAGABEABgARAAAQABIAAAAAAAAAAAAQABIAAQAAAAAAAAABBQASAAAAAAAFABIAAgAAAAAAAAABBgASAAAAAAABEQASAP////8RABIAAAAAAAAAAAARABIAAgAAAAAAAAABEgASAP////8BEQASAP////8SABIAAgAAAAAAAAAABwARAAcAEQAAAQYAEgAAAAAABgASAAEAAAAAAAAAAQQAEgAAAAAABwASAAUAAAAAAAAAAAMAEQADABEAAAETABIA/////wAEABEABAARAAAAAgARAAIAEQAAAQoAEgAAAAAAEwASAAAAAAAAAAAAEwASAAEAAAAAAAAAAQgAEgAAAAAACAASAAIAAAAAAAAAAQkAEgAAAAAAARQAEgD/////FAASAAAAAAAAAAAAFAASAAIAAAAAAAAAARUAEgD/////ARQAEgD/////FQASAAIAAAAAAAAAAAcAEQAHABEAAAEJABIAAAAAAAkAEgABAAAAAAAAAAEEABIAAAAAAAoAEgABAAAAAAAAAAEEABIAAAAAAAsAEgABAAAAAAAAAAABABEAAQARAAA=";
            }
        };
    }
    inline taul::grammar sigs() {
        return taul::internal::export_fetcher_singleton<details::sigs_singleton_traits>::fetch();
    }
}