#pragma once
#include <string_view>
#include <optional>
#include <taul/grammar.h>
#include <taul/export_fetcher.h>

namespace taul::fetchers {
    namespace details {
        struct sigs_singleton_traits final {
            static constexpr std::string_view get_serial_str() noexcept {
                return "TAULAQAAAAAAAAALAAAAAAAAAAkAAAAAAAAACgAAAElERU5USUZJRVIABwAAAFJfQVJST1cABwAAAExfUk9VTkQABwAAAFJfUk9VTkQACAAAAExfU1FVQVJFAAgAAABSX1NRVUFSRQAFAAAAQ09NTUEACQAAAERCTF9DT0xPTgAFAAAAQ09MT04ABQAAAFNMQVNIAAoAAABXSElURVNQQUNFAQgAAABUb3BMZXZlbAAEAAAARXhwcgMEAAAAQXJncwADAAAAQXJnAAgAAABDYWxsU3VmZgAGAAAAUGFyYW1zAAUAAABQYXJhbQAKAAAAUmV0dXJuVHlwZQACAAAASWQAIgAAAAAAAAABABEAAwAAAAAAAAABDAARAP////8BDgARAP////8BDwARAP////8MABEAAAAAAAAAAAAMABEAAQAAAAAAAAABDQARAP////8NABEAAQAAAAAAAAAAJAAAACUAAAAADgARAAEAAAAAAAAAAEEAAABaAAAAAA4AEQABAAAAAAAAAABfAAAAXwAAAAAOABEAAQAAAAAAAAAAYQAAAHoAAAAADgARAAEAAAAAAAAAAIAAAAD/1wAAAA4AEQABAAAAAAAAAAAA4AAA//8QAAAPABEAAAAAAAAAAAAPABEAAgAAAAAAAAABEAARAP////8BDwARAP////8QABEAAQAAAAAAAAAAMAAAADkAAAAAEAARAAEAAAAAAAAAAEEAAABaAAAAABAAEQABAAAAAAAAAABfAAAAXwAAAAAQABEAAQAAAAAAAAAAYQAAAHoAAAAAEAARAAEAAAAAAAAAAIAAAAD/1wAAABAAEQABAAAAAAAAAAAA4AAA//8QAAACABEAAgAAAAAAAAAALQAAAC0AAAAAAD4AAAA+AAAAAAMAEQABAAAAAAAAAAAoAAAAKAAAAAAEABEAAQAAAAAAAAAAKQAAACkAAAAABQARAAEAAAAAAAAAAFsAAABbAAAAAAYAEQABAAAAAAAAAABdAAAAXQAAAAAHABEAAQAAAAAAAAAALAAAACwAAAAACAARAAIAAAAAAAAAADoAAAA6AAAAAAA6AAAAOgAAAAAJABEAAQAAAAAAAAAAOgAAADoAAAAACgARAAEAAAAAAAAAAC8AAAAvAAAAAAsAEQABAAAAAAAAAAERABEA/////xEAEQACAAAAAAAAAAETABEA/////wESABEA/////xIAEQAAAAAAAAAAABIAEQACAAAAAAAAAAETABEA/////wESABEA/////xMAEQABAAAAAAAAAAEUABEA/////xQAEQABAAAAAAAAAAAJAAAACgAAAAAUABEAAQAAAAAAAAAADQAAAA0AAAAAFAARAAEAAAAAAAAAACAAAAAgAAAAABwAAAAAAAAAAwASAAMAAAAAAAAAAQQAEgAAAAAAAQwAEgD/////AAIAEgACABIAAQwAEgAAAAAAAAAAAAwAEgABAAAAAAAAAAEHABIAAAAAAAQAEgADAAAAAAAAAAENABIA/////wEOABIA/////wMNABIAAQAAAAAAAAABCwASAAAAAAAOABIAAAAAAAAAAAAOABIAAgAAAAAAAAABDwASAP////8BDgASAP////8PABIAAwAAAAAAAAACAAAAAP////8ACgARAAoAEQAAAQsAEgAAAAAADwASAAMAAAAAAAAAAgEAAAD/////AAkAEQAJABEAAAELABIAAAAAAA8AEgADAAAAAAAAAAICAAAA/////wAIABEACAARAAABCwASAAAAAAAPABIABAAAAAAAAAACAwAAAP////8ABQARAAUAEQAAARAAEgD/////AAYAEQAGABEAABAAEgAAAAAAAAAAABAAEgABAAAAAAAAAAEFABIAAAAAAAUAEgACAAAAAAAAAAEGABIAAAAAAAERABIA/////xEAEgAAAAAAAAAAABEAEgACAAAAAAAAAAESABIA/////wERABIA/////xIAEgACAAAAAAAAAAAHABEABwARAAABBgASAAAAAAAGABIAAQAAAAAAAAABBAASAAAAAAAHABIABQAAAAAAAAAAAwARAAMAEQAAARMAEgD/////AAQAEQAEABEAAAACABEAAgARAAABCgASAAAAAAATABIAAAAAAAAAAAATABIAAQAAAAAAAAABCAASAAAAAAAIABIAAgAAAAAAAAABCQASAAAAAAABFAASAP////8UABIAAAAAAAAAAAAUABIAAgAAAAAAAAABFQASAP////8BFAASAP////8VABIAAgAAAAAAAAAABwARAAcAEQAAAQkAEgAAAAAACQASAAEAAAAAAAAAAQQAEgAAAAAACgASAAEAAAAAAAAAAQQAEgAAAAAACwASAAEAAAAAAAAAAAEAEQABABEAAA==";
            }
        };
    }
    inline taul::grammar sigs() {
        return taul::internal::export_fetcher_singleton<details::sigs_singleton_traits>::fetch();
    }
}