#pragma once
#include <string_view>
#include <optional>
#include <taul/grammar.h>
#include <taul/export_fetcher.h>

namespace taul::fetchers {
    namespace details {
        struct sigs_singleton_traits final {
            static constexpr std::string_view get_serial_str() noexcept {
                return "TAULAQAAAAAAAAAIAAAAAAAAAAUAAAAAAAAACgAAAElERU5USUZJRVIACAAAAExfU1FVQVJFAAgAAABSX1NRVUFSRQAFAAAAQ09NTUEACQAAAERCTF9DT0xPTgAFAAAAQ09MT04ABQAAAFNMQVNIAAoAAABXSElURVNQQUNFAQgAAABUb3BMZXZlbAAEAAAARXhwcgMEAAAAQXJncwADAAAAQXJnAAIAAABJZAAfAAAAAAAAAAEAEQADAAAAAAAAAAEJABEA/////wELABEA/////wEMABEA/////wkAEQAAAAAAAAAAAAkAEQABAAAAAAAAAAEKABEA/////woAEQABAAAAAAAAAAAkAAAAJQAAAAALABEAAQAAAAAAAAAAQQAAAFoAAAAACwARAAEAAAAAAAAAAF8AAABfAAAAAAsAEQABAAAAAAAAAABhAAAAegAAAAALABEAAQAAAAAAAAAAgAAAAP/XAAAACwARAAEAAAAAAAAAAADgAAD//xAAAAwAEQAAAAAAAAAAAAwAEQACAAAAAAAAAAENABEA/////wEMABEA/////w0AEQABAAAAAAAAAAAwAAAAOQAAAAANABEAAQAAAAAAAAAAQQAAAFoAAAAADQARAAEAAAAAAAAAAF8AAABfAAAAAA0AEQABAAAAAAAAAABhAAAAegAAAAANABEAAQAAAAAAAAAAgAAAAP/XAAAADQARAAEAAAAAAAAAAADgAAD//xAAAAIAEQABAAAAAAAAAABbAAAAWwAAAAADABEAAQAAAAAAAAAAXQAAAF0AAAAABAARAAEAAAAAAAAAACwAAAAsAAAAAAUAEQACAAAAAAAAAAA6AAAAOgAAAAAAOgAAADoAAAAABgARAAEAAAAAAAAAADoAAAA6AAAAAAcAEQABAAAAAAAAAAAvAAAALwAAAAAIABEAAQAAAAAAAAABDgARAP////8OABEAAgAAAAAAAAABEAARAP////8BDwARAP////8PABEAAAAAAAAAAAAPABEAAgAAAAAAAAABEAARAP////8BDwARAP////8QABEAAQAAAAAAAAABEQARAP////8RABEAAQAAAAAAAAAACQAAAAoAAAAAEQARAAEAAAAAAAAAAA0AAAANAAAAABEAEQABAAAAAAAAAAAgAAAAIAAAAAASAAAAAAAAAAMAEgACAAAAAAAAAAEEABIAAAAAAAACABIAAgASAAEEABIAAwAAAAAAAAABCAASAP////8BCQASAP////8DCAASAAEAAAAAAAAAAQcAEgAAAAAACQASAAAAAAAAAAAACQASAAIAAAAAAAAAAQoAEgD/////AQkAEgD/////CgASAAMAAAAAAAAAAgAAAAD/////AAcAEQAHABEAAAEHABIAAAAAAAoAEgADAAAAAAAAAAIBAAAA/////wAGABEABgARAAABBwASAAAAAAAKABIAAwAAAAAAAAACAgAAAP////8ABQARAAUAEQAAAQcAEgAAAAAACgASAAIAAAAAAAAAAgMAAAD/////AQUAEgAAAAAABQASAAMAAAAAAAAAAAIAEQACABEAAAELABIA/////wADABEAAwARAAALABIAAAAAAAAAAAALABIAAQAAAAAAAAABDAASAP////8MABIAAgAAAAAAAAABBgASAAAAAAABDQASAP////8NABIAAAAAAAAAAAANABIAAgAAAAAAAAABDgASAP////8BDQASAP////8OABIAAgAAAAAAAAAABAARAAQAEQAAAQYAEgAAAAAABgASAAEAAAAAAAAAAQQAEgAAAAAABwASAAEAAAAAAAAAAAEAEQABABEAAA==";
            }
        };
    }
    inline taul::grammar sigs() {
        return taul::internal::export_fetcher_singleton<details::sigs_singleton_traits>::fetch();
    }
}